node("centos"){
    stage("Git checkout"){
        git url: 'git@github.com:aragastmatb/example-playbook.git'
    }
    stage("Sample define secret_check"){
        secret_check=true
    }
    def is_prod = "${env.IS_PROD}"
    if (secret_check){
        if (env.IS_PROD == "true"){
            stage("Run prod"){    
                sh 'ansible-playbook site.yml -i inventory/prod.yml'
            }
        else{
            stage("Run test"){    
                sh 'ansible-playbook site.yml -i inventory/prod.yml --check --diff'
            }
        }
    }
}
