---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos
    image: centos:8
    dockerfile: ../resources/Dockerfile.j2
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  playbooks:
    verify: ../resources/verify.yml
verifier:
  name: ansible
