---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: host
    image: registry.access.redhat.com/ubi8/ubi-init
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
